In [10]:
import numpy as np
import tensorflow as tf

x_data =  [[1, 2, 1, 1],
            [2, 1, 3, 2],
            [3, 1, 3, 4],
            [4, 1, 5, 5],
            [1, 7, 5, 5],
            [1, 2, 5, 6],
            [1, 6, 6, 6],
            [1, 7, 7, 7]]

y_data =   [[0, 0, 1],
            [0, 0, 1],
            [0, 0, 1],
            [0, 1, 0],
            [0, 1, 0],
            [0, 1, 0],
            [1, 0, 0],
            [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data)).batch(len(x_data))

W = tf.Variable(tf.random.normal([4, 3], name='weight'))
b = tf.Variable(tf.random.normal([3], name='bias'))

dataset.element_spec

def cost_fn(features, labels):
    hypothesis = tf.nn.softmax(tf.matmul(features, W) + b)
    cost = tf.reduce_mean(-tf.reduce_sum(labels * tf.math.log(hypothesis), axis=1))
    return cost

def grad(features, labels):
    with tf.GradientTape() as tape:
        cost_value = cost_fn(features, labels)
    return tape.gradient(cost_value, [W, b])

optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)

EPOCHS = 2400

for step in range(EPOCHS + 1):
    for features, labels in iter(dataset):
        grads = grad(features, labels)
        optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
        if step % 300 == 0:
            print("iter : {}, cost : {:.4f}".format(step, cost_fn(features, labels)))

iter : 0, cost : 4.3906
iter : 300, cost : 0.4929
iter : 600, cost : 0.3799
iter : 900, cost : 0.2760
iter : 1200, cost : 0.2174
iter : 1500, cost : 0.1905
iter : 1800, cost : 0.1693
iter : 2100, cost : 0.1522
iter : 2400, cost : 0.1381


In [12]:
a = x_data
a = tf.nn.softmax(tf.matmul(a, W) + b)

print("Hypothesis : {}".format(a))

# argmax: 가장 큰 값의 index를 반환합니다.
print(tf.argmax(a, axis=1))         # 예측 값 by Hypothesis
print(tf.argmax(y_data, axis=1))    # 실제 값

Hypothesis : [[6.47958529e-07 7.50564504e-04 9.99248803e-01]
 [1.99433096e-04 6.75592497e-02 9.32241380e-01]
 [5.84766902e-09 1.40294775e-01 8.59705210e-01]
 [8.47631796e-08 8.73523057e-01 1.26476869e-01]
 [2.33241811e-01 7.56763995e-01 9.99415293e-03]
 [1.23562574e-01 8.76400530e-01 3.68698165e-05]
 [7.60851204e-01 2.39121065e-01 2.77535546e-05]
 [9.38371420e-01 6.16282895e-02 3.26691605e-07]]
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
